backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "posts"
    label: "Posts"
    files:
      - name: "data"
        label: "Blog Posts Data"
        file: "data/posts.json"
        description: "All blog posts are stored in this file"
        fields:
          - name: "posts"
            label: "Posts"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Publish Date", name: "date", widget: "datetime"}
              - {label: "Featured Image", name: "image", widget: "image", required: false}
              - {label: "Body", name: "body", widget: "markdown"}
